# Project-wide configuration.
PROJECT_NAME = collision-monitor
VENV_NAME = ".venv"
PYTHON_VENV = ${VENV_NAME}/bin/python

# Docker Config
DOCKERFILE := aws.Dockerfile
DOCKERCOMPOSE_FILE := docker-compose.yml

# Test Config
TEST_VERBOSE := 1
TEST_COVERAGE := 1
